<!DOCTYPE html>
<?php include "comment.php";?>
<html dir="ltr" lang="en">
  <head>
    <title>The Cavern</title>
    <?php include "meta.php";?>
  </head>
  <body>
    <?php include "header.php";?>
      <p><a href="Underground-Stream">Gasping for air, she crawled from the stream</a> into the echoing darkness of a cavern, dripping water onto the rocks.</p>
      <p>She lay shivering alone on the rocks, listening to the echoing ripples of the stream behind her. Wet strands of her hair were matted to her face. She could feel the water on her skin gradually dry. When she felt warm enough to move again she reached down to touch her belt. Her knife and her flint were still strapped into the sheath. She patted her hair. Aside from some clumps that were still damp at the tip, her hair felt dry. She rose gingerly from the rocks. Twisting her hair into a thick lock, she hacked off her hair at her shoulders. She crouched to set her hair on the rocks, poured a splash of turpentine from the container, and then struck her knife against her flint to spark a blaze.</p>
      <p>She could see in an instant that the cavern was a dead-end. A craggy dome of granite containing a chamber of empty space. She was alone. Alone, she realized, except for something on the wall directly across from the stream. She walked across the cavern, gazing at the wall in a trance. There was a painting there. A scene of galloping bison, and below that, like a signature, a human handprint, all rendered in <a href="Red-Orange">a vibrant shade of red-orange.</a> Realizing the painting had been created by a human from centuries past, she felt a shiver of goosebumps down the skin on the back of her neck, laughing in awe. Aside from the artist, she thought, she might be the only human to have ever seen this painting. She loved the style in which the bison had been depicted, the pleasing juxtaposition between the curving slashes of the horns and the hefty shapes of the heads, the satisfying proportions between the bulbous figures of the bodies and the spindly lines of the legs, the extraordinary sense of movement the artist had captured, and also the strangely charming personality of the handprint underneath, which seemed somehow to possess an air of friendliness, even amusement. What a miracle to have found this, she thought. The artist had selected a glossy oblong slab of granite as a canvas for the painting, yet only half of the slab had been covered, she realized, while the other half of the slab remained blank, as if reserved for some unknown purpose. Behind her the light of the fire abruptly flickered out into darkness.</p>
      <p>Clara stood there alone for a while in the darkness, considering what to do. She touched her shirt. She touched her trousers. The fabric felt dry. Reaching into her pockets, she took out her supplies, carefully arranging the vials of pigment and the vessel of oil at her feet, along with the container of turpentine. She became aware that her heart was pounding, so aflutter with nervousness and excitement and anticipation that she felt almost dizzy. She set down her belt. Then she thumbed the buttons through the buttonholes in her shirt and her trousers, slipping her shirt off, dropping her trousers too. Squatting over the rocks in her undergarments, she carefully gathered her shirt and her trousers into a crumpled heap and shook splashes of turpentine onto the fabric until the container was empty and then grabbed her knife and her flint and struck a spark. Once her garments were blazing she swiveled back toward the wall in the flickering glow of the flames, cupping her hand to use as a palette, tapping some pigment into her palm, drizzling some oil into her palm, then carefully mixing the pigment into the oil with her fingers, blending <a href="Yellow-Orange">a radiant shade of yellow-orange,</a> and then scooping a dollop of paint onto the tip of her finger. Thinking about the most beautiful sight she&rsquo;d ever seen, with brisk fluid strokes she painted a scene of flitting hummingbirds on the wall, taking some time afterward to touch up certain areas of the composition with dabs of color. When she realized the light of the flames was already fading, she felt a sense of alarm, quick stripping off her undergarments and bunching up the fabric and sticking the fabric in and then crouching to blow on the fire, and for a moment the flames dimmed, but then the flames flared bright again, and with a sense of urgency she hurried to pour the oil over the last of the pigment, smearing paint across her hand, rubbing paint into the grooves at the joints of her fingers, daubing paint onto the wrinkles in the flesh of her palm, and then she carefully pressed a handprint into the wall. The light of the flames was already fading again. Shivering at the chill in the air, she stepped back from the wall to gaze at <a href="The-Paintings">the paintings.</a> The flames flickered out into darkness.</p>
      <p>Afterward she knelt naked by the stream, drinking gulps of water. She wiped dripping water from her chin with the back of a wrist. She breathed. She was so hungry she was trembling. She stood again. She walked back across the cavern. She sat on the rocks with her elbows resting on her knees. Staring into the darkness, she thought for a while about all of the wonderful surprises life had given her over the past year. She&rsquo;d dreamed of <a href="Kentucky-11888-HE">finding a mentor,</a> of getting to paint <a href="Oklahoma-Territory-11888-HE">day and night,</a> of painting <a href="Utah-Territory-11888-HE">desert landscapes</a> and <a href="Wyoming-Territory-11888-HE">forest landscapes</a> and <a href="Montana-Territory-11888-HE">mountain landscapes</a> en plein air. Of someday painting something truly special. She understood that she would die in that cavern, that eventually she would starve, and she did feel fear, and she did feel despair, but what she felt most of all was a sense of gratitude. An everlasting thanks. She had never wanted a romantic relationship. She had never experienced a carnal desire. And still, back in civilization, seeing loving couples in passing on the street, she&rsquo;d sometimes felt a terrible sadness, envious of that special intimacy that so many human couples shared. She&rsquo;d imagined that she would die without ever feeling an intimacy that powerful. But when she thought about the act that she&rsquo;d just committed in that cavern, she could imagine nothing more intimate. To have formed a secret connection across centuries with another human. The making of a singular artistic relationship. The expression of a mutual artistic desire. Sitting there naked in the darkness of the cavern, she struck her knife against her flint, then struck again, and struck again, marveling by those dazzling flashes of light at the paintings on the wall.</p>
    <?php include "footer.php";?>
  </body>
</html>