<!DOCTYPE html>
<?php include "comment.php";?>
<html dir="ltr" lang="en">
  <head>
    <title>The Human Story</title>
    <?php include "meta.php";?>
  </head>
  <body>
    <?php include "header.php";?>
      <p><a href="Deluge">They sat alone at a bus stop,</a> sheltered from the rain by the glass canopy over the bench, hunched and shivering at the wind. The sidewalks were deserted. The neon glow of the traffic light at the intersection shimmered across the rippling pools in the road. Zoe finally began to cry, at first because she was hungry, because she wanted to brush her teeth and she couldn&rsquo;t, because she wanted to shave her legs and she couldn&rsquo;t, because she just wanted to put her hair up to get her hair out of her face and now she didn&rsquo;t even have a hair tie, because now she didn&rsquo;t even have socks or a bra, but then suddenly as she was sobbing her tone changed, became hollow and desperate and raw, and she began to speak of a permanent sadness, confessing something to him that she had never told him before. Every human was a story, she said, and she was so happy to be a human and to have a life and to be a story, but one day when she was a child she had realized that she would never be another person, that the only life she would ever live was just the single life she was living, and because she believed that every human was miraculous and fascinating and lived a life of profound mystery and tragedy and comedy and beauty, this realization had haunted her, and yet the most terrible realization of all had been when she&rsquo;d suddenly understood that the story of any particular human was ultimately only an episode in a far greater story, that together over millions of years the human species had lived billions of intersecting and overlapping and yet all fundamentally unique lives, and that this all-story, the story of the human species across space and time, every moment of every life, was the most epic story imaginable, even just imagining the vague blurry outline of the story had made her heart ache at the catastrophic beauty, and she&rsquo;d desperately longed for the ability to know every detail, to somehow move between human lives across space and time, to experience the untold stories of the human species from the first to the last, but even as a child she&rsquo;d understood that was impossible, just utterly impossible, and so she had been heartbroken ever since, and she was going to be heartbroken forever.</p>
      <p>When she was finished crying, she sniffled for a while, wiping some tears from her cheeks in silence. Jay reached over to wrap an arm around her, and then she leaned into him, resting her head on his shoulder as rainwater flooded the gutters, surging into the storm drains.</p>
      <p>&ldquo;I just wish there was a way to see it,&rdquo; Zoe murmured.</p>
      <p>A bus arrived, coming to a halt with a hiss of brakes. The driver opened the door, looking out at them as if expecting them to rise from the bench and climb into the warmth of the bus. They didn&rsquo;t board. They couldn&rsquo;t afford the fare.</p>
    <?php include "footer.php";?>
  </body>
</html>