<!DOCTYPE html>
<?php include "comment.php";?>
<html>
  <head>
    <title>The Cave</title>
    <?php include "meta.php";?>
  </head>
  <body>
    <?php include "header.php";?>
        <p><a href="The-Ruins-Of-A-Tent">Hiking along a rocky slope in the forest in the pouring rain,</a> she noticed a ledge jutting out over some ferns, and when she approached the ledge she discovered that the ferns hid what appeared to be the entrance to a cave. Switching her headlamp on, she squatted there in the dirt for a moment, peering into the cave, and then she switched her headlamp off again, crawling under the ledge.</p>
        <p>The cave was dry. Twilight was falling across the forest. Em took off her backpack. Her canteen was empty. She reached back out beyond the ledge to set her canteen in the rain. Then she stripped off the poncho and tugged apart the knots in the laces of her boots and wrenched her boots off and tossed her boots aside, and then she peeled off her socks, sitting there barefoot in the cave in her sweatshirt and her leggings with her hair in a bun. Her feet were aching, and she arched her toes out and curled her toes in and then wiggled her toes up and down to stretch the soles of her feet, and then she drew her feet to her body, rubbing the soles of her feet with her hands, digging her thumbs into the pads of flesh on the soles, then grinding the bony lumps of her knuckles across the arches, then kneading the arches with the sharp heels of her palms, grunting in pleasure. She massaged the back of her neck. Her stomach was gurgling. She&rsquo;d been trying to ration the food in her backpack. She was too hungry. Sitting there in the cave she ate <a href="Hunger">the apple and the cheese,</a> alternating bites to mix the flavors as she was chewing, and then she ate the rest of the chocolate. She felt a rush of joy as the sugar and the salt and the fat and the caffeine hit her bloodstream. She burst out laughing, amazed by the feeling. She licked sticky juice from her lips. She sucked oily grease from her fingers. She drank rainwater from her canteen. When she was satisfied she leaned back against the slope of the cave, putting on the tortoiseshell eyeglasses from her backpack. She took out the notebook and the pencil. Biting the pencil between her teeth, she flipped through the notebook until she reached <a href="Ems-Latest-Entry">the latest entry.</a> She read over what she had written. She thought about writing a new entry. She decided that she was too sleepy. Setting aside the notebook and the pencil, she slipped off the tortoiseshell eyeglasses, and then she gazed for a while at the rain drizzling onto the ferns in the forest. She had always loved <a href="The-Most-Beautiful-Genre-Of-Music-In-The-World">falling asleep to the sound of rain.</a> Feeling a chill, she tugged her socks back onto her feet and wrapped the emergency blanket around her body, and then she lay down on the dirt, facing out toward the ferns as darkness fell across the forest. She wondered if she would die before <a href="Sunrise">morning.</a></p>
      <?php include "footer.php";?>
  </body>
</html>