<!DOCTYPE html>
<?php include "comment.php";?>
<html dir="ltr" lang="en">
  <head>
    <title>Underground Stream</title>
    <?php include "meta.php";?>
  </head>
  <body>
    <?php include "header.php";?>
        <p><a href="The-Pit">She dipped her hand into the stream,</a> touching the frigid gleaming water. The current was gentle. Ahead of her the stream appeared to flow into a gap beneath a craggy ledge. Clara took off her boots, standing barefoot on the rocks. The sketches were burning quickly. The glittering gold dust in the stream seemed to vanish as the light of the flames faded. Setting her boots aside, she stepped into the water in her shirt and her trousers, whimpering in reflex at the shock of the cold. She waded out into the stream until the water was lapping at her neck. A glowing wisp of paper floated past her, flaring brightly before disappearing. She whispered a prayer, and then the faint light of the flames behind her flickered out into darkness, and standing there alone in the water in the darkness she breathed out and breathed in and then plunged under the surface of the stream, swimming through the water with her eyes shut and her arms outstretched and her legs fluttering. She knew that she&rsquo;d followed the stream under the ledge when she felt the back of her head bump against a crag on the rocky ceiling underwater. She could hear the murky rippling of the stream around her. Hollow thunks. Muffled plunks. The fabric of her shirt and her trousers pulsed against the skin on her arms and her legs as she lurched through the water. Her knuckles scraped against a lumpy crag above her. Above her her heel knocked against a sharp crag. She bumped the back of her head again. Becoming aware of a tightness in her lungs, she felt a jolt of fear. She kept swimming, desperately praying, hoping, begging, touching nothing but the water and the rocks trapping her beneath the surface. When the tightness in her lungs became crushing, she began to panic, realizing that she almost out of breath, and then she was out of breath, needed to breathe, and her eyes opened on reflex but there was still only darkness ahead of her, gulping down water, thrashing wildly through the darkness, gripped by a primal animal terror, reaching, kicking, drowning, alone, and then above her suddenly her hands touched air and with a frantic jerk of her legs she <a href="The-Cavern">burst back above the surface of the stream.</a></p>
      <?php include "footer.php";?>
  </body>
</html>