<!DOCTYPE html>
<?php include "comment.php";?>
<html dir="ltr" lang="en">
  <head>
    <title>One About The Chorus</title>
    <?php include "meta.php";?>
  </head>
  <body>
    <?php include "header.php";?>
      <?php include "0.php";?> and later that year the child was born, in a busy urban hospital on the chilly autumn morning of November 6, 1985. If he&rsquo;d been a girl, his parents would have named him Megan, but instead his parents named him William.</p>
      <p>When he was one his father drowned at a beach, and when he was five he and his mother ate a cinnamon pretzel together in the sunlight on a granite bench by a fountain in a shopping mall, and when he was seven he and his mother ate some enchiladas together at the table in the kitchen as fog drifted past the window, and when he was nine he and his mother ate some stroganoff together at the table in the kitchen as mist trickled down the window, and when he was fourteen he and his mother ate garlic bread and lasagna and broccoli together at the table in the kitchen as fireflies twinkled in the twilight, and later that night he smoked a joint at a party, lying with a cluster of strangers on a trampoline in the darkness while frogs chirped in the woods.</p>
      <p>A year later he smoked a joint in the shimmering light of a lava lamp, thinking about koans.</p>
      <p>A year later he smoked a joint in the flickering light of a plasma globe, thinking about cubism.</p>
      <p>A year later he smoked a joint in the glittering light of a disco ball, thinking about nebulas.</p>
      <p>Valedictorian.</p>
      <p>Harvard on scholarship.</p>
      <p>Freshman year of college one morning he was sitting at a table in the library reading a textbook about physics when he suddenly heard a voice singing.</p>
      <p>Startled, he glanced around, but he was the only one in the library who seemed to notice the singing voice.</p>
      <p>He could still hear the voice singing as he walked from the library to the cafeteria.</p>
      <p>He could still hear the voice singing as he poured grapefruit juice into a cup.</p>
      <p>He could still hear the voice singing as he chewed a plate of scrambled eggs.</p>
      <p>As he walked from the cafeteria back to the dorm other voices began to sing.</p>
      <p>At first the voices frightened him, but as the weeks passed he began to adjust to the strangeness of what was happening, and he gradually began to feel curious about the voices, and he even began to feel fond of the voices, fascinated by what he heard. Sometimes instead of singing the voices would speak. Weather reports, astrological predictions, cosmetology tips, lifeguard banter, lyric poetry, religious mantras, election debates, boardroom gossip, military jargon, terrorist manifestos, calculus lectures, subway announcements, bartender chatter. But often the voices sang. Enchanting, reverberating, vibrant, trebles and sopranos and altos and tenors and baritones and basses, some enunciating in foreign accents or foreign dialects or foreign tongues. Periodically fading in and out like garbled snatches of radio transmissions coming in and out of range of a receiver. Dissonant harmony. Harmonious dissonance. For months he lived with the voices in secret. Wondering if the voices were imaginary. Wondering if the voices were real. If maybe what he was hearing were voices from another time or another space. If he had a special power.</p>
      <p>When his mother discovered he was hearing voices, his mother brought him to visit a psychiatrist, but by then he was too obsessed to care about a diagnosis.</p>
      <p>He quit going to class.</p>
      <p>&ldquo;Just take the medication,&rdquo; his mother begged, wearing a denim jacket, crying across from him in a booth at a diner as rain fell in the darkness beyond her.</p>
      <p>He dropped out of college instead. Rode a bus across the country. California. Decided to live in a tent. Panhandled for cash during the day. Drank cups of soda. Drank bottles of cola. Ate one-dollar cheeseburgers, licking the grease from the wrappers. Licked crystals of salt from bags of fries. Sucked on packets of ketchup. Sucked on packs of honey. Bathed at twilight under the showers at the beach. Smoked marijuana in the dusk. Sunburned, bloodshot, with a tangled beard, a ripped shirt, some ragged pants, dusty feet. Shuffling barefoot across intersections. Wandering through plazas. Drifting through parks. Listening to the voices in reverie. His mother probably looked for him. He never saw his mother again. He lived on the street for decades. Managed to survive until the age of forty-one. By then he had no tent, just some musty blankets on a heap of rotten cardboard on a slab of concrete under a bridge. Daybreak was glowing in the sky. He could hear pigeons cooing above him where he lay. A car rumbled across the bridge. A truck clattered across the bridge. A breeze blew. Then there was silence. He lay there staring at the beams on the underside of the bridge, overcome with despair. For a week the voices had been silent. The voices had never disappeared that long before, at most only ever disappearing for an hour or a day, and after a week of silence he was terrified that now the voices might never return. Desperate. Blinking at the beams on the underside of the bridge with tears shimmering in his eyes. Grimy fingernails, a greasy cotton sweatsuit, cracked toenails. Muttering in anguish. Mumbling in despair. Begging for the voices to return. Dawn was burning a radiant pink-gold in the sky. Light gleamed on an empty glass bottle lying on the concrete beside him. A glimmer. Beyond the bridge the palm trees rippled with the wind, and then suddenly with a sense of shock he realized that he could hear a voice singing again, a warbling lilt, and he cried out in relief, smiling, and then one by one other voices began to sing too, quietly but becoming louder, and the concrete began to tremble and the bottle shuddered on the concrete and the bottle bounced on the concrete and the pigeons fluttered away and ripples of dust floated down from the beams on the underside of the bridge as the bridge began to jolt and wobble and shake and the voices erupted into a chorus, chanting a multidimensional sequence of overlapping melodies, resounding. As the earthquake struck full blast he heard one of the voices hit a note that seemed almost ultrasonic, ringing with a breathtaking clarity. The most beautiful sound he&rsquo;d ever heard. A moment later the bridge collapsed.</p>
    <?php include "footer.php";?>
  </body>
</html>