<!DOCTYPE html>
<?php include "comment.php";?>
<html>
  <head>
    <title>The One About The Variations</title>
    <?php include "meta.php";?>
  </head>
  <body>
    <?php include "header.php";?>
        <?php include "0.php";?> but later that year before the child could be born the parents were killed, in a car-flipping smash-up on a highway in the city on the rainy summer evening of August 28, 1985. The child was delivered by shouting medics. Lived for months in an incubator in a hospital. Survived apnea. Survived pneumonia. Survived sepsis. Survived. There was no record of what the parents had intended to name the child, if the parents had ever even had a chance to decide on a name. When the child was finally released from the hospital, he was raised by relatives who named him Clay.</p>
        <p>He was deaf. Liked butterflies. Loved kittens. Average grades. Became a mail carrier. Lived alone in a house with painted shutters. Oak tree in the yard. Had a reputation for shyness. Neighbors occasionally spotted him carrying in groceries, or fetching the newspaper, or planting flowers, or raking leaves. Pouring birdseed into the birdfeeder by the oak tree. Otherwise he was rarely encountered. A lamp glowing in a window. Neighbors assumed that at night he was probably just watching television. Secretly though, at night he was a writer. Hunched over sheets of paper at the table in the kitchen, writing stories by hand. Every story that he wrote was a variation of the same story. Identical beginnings that inevitably diverged into radically different conclusions. He organized the manuscripts in colored folders in a box in a closet. By the time that he died, at the age of sixty-four, he had written hundreds of versions. The manuscripts were found by a cousin, who had a friend who worked at a library at a university, who arranged to exhibit the manuscripts in a display in the lobby, where the manuscripts were noticed by a banker, who decided to pay for the manuscripts to be published as a collection. A hardcover volume was printed. The book was niche. Less than one thousand copies purchased. Most of the copies were eventually destroyed. Warped by rain. Spattered with coffee. Blotted with wine. Dropped in bathtubs. Fumbled in pools. Rotted with mold. Wrecked by mice. Tossed in dumpsters. Forgotten. A century later, the sole remaining copy was discovered by a celebrity deejay peeking through the drawers of an antique desk in the penthouse suite of a boutique hotel, who read the book that night while smoking a blunt on the balcony and then mentioned the book in an interview at a fashion show the next day, hyping the stories, praising the stories, producing a sudden explosion of interest. Paperback editions were printed. Mass-market. Within decades, there were academic publications devoted to the study of the book. Graffiti in tribute to the book. Monuments in honor of the book. Shrines glorifying the mythology. Festivals in celebration. At the end of the millennium, obsessed fans formed a community in the desert, developing a religion based on a mystical interpretation of the stories. After a year of harmony, the followers promptly divided into rival factions, insulting each other, threatening each other, attacking each other with rocks and knives and hammers and axes, launching a war that would ultimately result in the deaths of more than one billion human beings. In a note taped to the manuscripts, he&rsquo;d dedicated the project to his parents.</p>
        <?php include "randomize.php";?>
      <?php include "footer.php";?>
  </body>
</html>